version: '3'
services:
  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'

  backend:
    image: node:10.4.0
    ports:
      - '3000:3000'

  prostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
